import { timingSafeEqual } from 'crypto'
import { EventEmitter } from 'events'
import { createServer, IncomingMessage, Server, ServerResponse } from 'http'
import { AddressInfo } from 'net'
import { Duplex } from 'stream'
import { WebSocket, WebSocketServer } from 'ws'
import { TOKEN_HEADER, TOKEN_PARAM } from '../../bridge/network'
import {
  BRIDGE_PATH,
  ClientMessage,
  EventMessage,
  MissingHandlerError,
  ReplyMessage,
  serializeError,
} from '../../bridge/protocol'

/**
 * The renderer connection, as `xmcl-runtime` knows it. It is the sidecar's
 * replacement for Electron's `WebContents`: services keep it to push state
 * mutations to the window that subscribed to them.
 */
export class BridgeClient extends EventEmitter {
  /**
   * `ws` is absent for the sidecar itself, which calls channels locally through
   * {@link BridgeServer.invokeLocal} and has nothing to push events to.
   */
  constructor(private readonly ws: WebSocket | undefined, private readonly server: BridgeServer) {
    super()
    // One `destroyed` listener per service that tracks this window, and the
    // launcher has far more than ten of them.
    this.setMaxListeners(0)
  }

  isDestroyed() {
    if (!this.ws) return false
    return this.ws.readyState !== WebSocket.OPEN && this.ws.readyState !== WebSocket.CONNECTING
  }

  send(channel: string, ...payload: any[]) {
    if (!this.ws) return
    this.server.sendTo(this.ws, channel, payload)
  }
}

export interface BridgeEvent {
  sender: BridgeClient
}

export type BridgeHandler = (event: BridgeEvent, ...args: any[]) => unknown

/**
 * A plain HTTP route served next to the WebSocket. Used by the network proxy,
 * which needs streams and status codes the RPC protocol cannot carry.
 */
export type RouteHandler = (
  req: IncomingMessage,
  res: ServerResponse,
  url: URL,
) => void | Promise<void>

/**
 * Local RPC endpoint replacing Electron's intra-process IPC.
 *
 * Security notes, because moving IPC to a socket is a real regression surface:
 * the server binds loopback only, requires the per-launch token generated by
 * the Rust shell, and rejects cross-origin upgrades. A single WebSocket server
 * handles the upgrade manually: attaching several `WebSocketServer`s with
 * different `path`s to one HTTP server makes them race on the handshake.
 */
export class BridgeServer {
  private readonly handlers = new Map<string, { handler: BridgeHandler; once: boolean }>()
  private readonly clients = new Map<WebSocket, BridgeClient>()
  private readonly localListeners = new Map<string, Set<(...args: any[]) => void>>()
  private readonly routes = new Map<string, RouteHandler>()
  private readonly wss = new WebSocketServer({ noServer: true, maxPayload: 128 * 1024 * 1024 })
  private readonly http: Server = createServer((req, res) => this.onRequest(req, res))

  constructor(private readonly token: string, private readonly logger: Pick<Console, 'log' | 'warn' | 'error'> = console) {
    this.http.on('upgrade', (req, socket, head) => this.onUpgrade(req, socket, head))
    this.wss.on('connection', (ws) => this.onConnection(ws))
  }

  /** Register a channel, mirroring `ipcMain.handle`. */
  handle(channel: string, handler: BridgeHandler) {
    this.handlers.set(channel, { handler, once: false })
    return this
  }

  /** Register a channel consumed by the first call, like `ipcMain.handleOnce`. */
  handleOnce(channel: string, handler: BridgeHandler) {
    this.handlers.set(channel, { handler, once: true })
    return this
  }

  /**
   * Serve a plain HTTP path from the bridge server. Authenticated with the same
   * per-launch token as the socket, because these routes reach the runtime.
   */
  route(path: string, handler: RouteHandler) {
    this.routes.set(path, handler)
    return this
  }

  removeHandler(channel: string) {
    this.handlers.delete(channel)
    return this
  }

  /** Push an event to every connected window, like `webContents.send`. */
  broadcast(channel: string, ...args: unknown[]) {
    const message: EventMessage = { t: 'event', channel, args }
    const payload = JSON.stringify(message)
    for (const client of this.clients.keys()) {
      this.send(client, payload)
    }
    for (const listener of this.localListeners.get(channel) ?? []) {
      try {
        listener(...args)
      } catch (e) {
        this.logger.error(`[bridge] local '${channel}' listener failed`, e)
      }
    }
  }

  /**
   * Observe a broadcast from inside the sidecar. Modules that Electron ran in a
   * window's preload, such as the multiplayer peer, are windows as far as the
   * runtime is concerned and still need the events it sends to them.
   */
  onBroadcast(channel: string, listener: (...args: any[]) => void) {
    const listeners = this.localListeners.get(channel) ?? new Set()
    listeners.add(listener)
    this.localListeners.set(channel, listeners)
    return () => listeners.delete(listener)
  }

  /**
   * Call a channel from inside the sidecar. Used by the modules that moved out
   * of a preload: the runtime registers their channels on the controller, and
   * there is no window in between anymore.
   */
  async invokeLocal(channel: string, ...args: unknown[]) {
    const entry = this.handlers.get(channel)
    if (!entry) throw new MissingHandlerError(channel)
    if (entry.once) this.handlers.delete(channel)
    return await entry.handler({ sender: new BridgeClient(undefined, this) }, ...args)
  }

  /** Push an event to a single window, like `webContents.send`. */
  sendTo(client: WebSocket, channel: string, args: unknown[]) {
    const message: EventMessage = { t: 'event', channel, args }
    this.send(client, JSON.stringify(message))
  }

  get clientCount() {
    return this.clients.size
  }

  async listen(port: number) {
    await new Promise<void>((resolve, reject) => {
      this.http.once('error', reject)
      this.http.listen(port, '127.0.0.1', () => {
        this.http.removeListener('error', reject)
        resolve()
      })
    })
    return (this.http.address() as AddressInfo).port
  }

  async close() {
    for (const client of this.clients.keys()) client.close()
    this.clients.clear()
    await new Promise<void>((resolve) => this.http.close(() => resolve()))
  }

  /**
   * `libdatachannel`-style backpressure lesson applies here too: a webview
   * that stops reading must not grow the send buffer without bound. Drop the
   * connection instead of letting the sidecar's heap follow it.
   */
  private send(client: WebSocket, payload: string) {
    if (client.readyState !== WebSocket.OPEN) return
    if (client.bufferedAmount > 64 * 1024 * 1024) {
      this.logger.warn('[bridge] client is not draining; closing it')
      client.terminate()
      return
    }
    client.send(payload)
  }

  private onRequest(req: IncomingMessage, res: ServerResponse) {
    if (!this.isLoopback(req)) {
      res.writeHead(403).end()
      return
    }
    const url = new URL(req.url ?? '/', 'http://127.0.0.1')
    const handler = this.routes.get(url.pathname)
    if (!handler) {
      res.writeHead(404).end()
      return
    }
    const header = req.headers[TOKEN_HEADER]
    const token = url.searchParams.get(TOKEN_PARAM) ?? (Array.isArray(header) ? header[0] : header) ?? null
    if (!this.isAuthorized(token)) {
      this.logger.warn(`[bridge] rejected ${url.pathname}: invalid token`)
      res.writeHead(401).end()
      return
    }
    void Promise.resolve(handler(req, res, url)).catch((e) => {
      this.logger.error(`[bridge] route '${url.pathname}' failed`, e)
      if (!res.headersSent) res.writeHead(500)
      res.end()
    })
  }

  private isLoopback(req: IncomingMessage) {
    const remote = req.socket.remoteAddress ?? ''
    return remote === '127.0.0.1' || remote === '::1' || remote === '::ffff:127.0.0.1'
  }

  private onUpgrade(req: IncomingMessage, socket: Duplex, head: Buffer) {
    const reject = (reason: string) => {
      this.logger.warn(`[bridge] rejected upgrade: ${reason}`)
      socket.destroy()
    }
    if (!this.isLoopback(req)) {
      return reject(`non-loopback peer ${req.socket.remoteAddress ?? ''}`)
    }
    const url = new URL(req.url ?? '/', 'http://127.0.0.1')
    if (url.pathname !== BRIDGE_PATH) {
      return reject(`unknown path ${url.pathname}`)
    }
    if (!this.isAuthorized(url.searchParams.get('token'))) {
      return reject('invalid token')
    }
    this.wss.handleUpgrade(req, socket, head, (ws) => this.wss.emit('connection', ws, req))
  }

  private isAuthorized(token: string | null) {
    if (!token) return false
    const expected = Buffer.from(this.token)
    const actual = Buffer.from(token)
    return expected.length === actual.length && timingSafeEqual(expected, actual)
  }

  private onConnection(ws: WebSocket) {
    const client = new BridgeClient(ws, this)
    this.clients.set(ws, client)
    this.logger.log(`[bridge] window connected (${this.clients.size} total)`)
    ws.on('close', () => {
      this.clients.delete(ws)
      client.emit('destroyed')
      this.logger.log(`[bridge] window disconnected (${this.clients.size} left)`)
    })
    ws.on('error', (e) => this.logger.warn(`[bridge] socket error: ${e.message}`))
    ws.on('message', (data, isBinary) => {
      if (isBinary) {
        this.logger.warn('[bridge] ignoring binary frame')
        return
      }
      let message: ClientMessage
      try {
        message = JSON.parse(data.toString())
      } catch {
        this.logger.warn('[bridge] ignoring malformed frame')
        return
      }
      void this.dispatch(ws, message)
    })
  }

  private async dispatch(ws: WebSocket, message: ClientMessage) {
    if (typeof message?.channel !== 'string' || !Array.isArray(message.args)) {
      this.logger.warn('[bridge] ignoring frame with an invalid shape')
      return
    }
    if (message.t === 'send') {
      await this.call(ws, message.channel, message.args).catch((e) =>
        this.logger.error(`[bridge] '${message.channel}' failed: ${e?.message ?? e}`),
      )
      return
    }
    if (message.t !== 'invoke' || typeof message.id !== 'number') {
      this.logger.warn('[bridge] ignoring frame with an unknown type')
      return
    }
    let reply: ReplyMessage
    try {
      reply = { t: 'reply', id: message.id, ok: true, result: await this.call(ws, message.channel, message.args) }
    } catch (e) {
      reply = { t: 'reply', id: message.id, ok: false, error: serializeError(e) }
    }
    this.send(ws, JSON.stringify(reply))
  }

  private async call(ws: WebSocket, channel: string, args: unknown[]) {
    const entry = this.handlers.get(channel)
    if (!entry) throw new MissingHandlerError(channel)
    if (entry.once) this.handlers.delete(channel)
    const sender = this.clients.get(ws)
    if (!sender) throw new Error(`The client of '${channel}' is gone`)
    return await entry.handler({ sender }, ...args)
  }
}
